* Customizing Gnus to work Yahoo mail

** These are my settings for receiving and sending mail.

To receive mail, the (=~/.gnus.el=) file is configured as follows:

#+BEGIN_SRC
(setq user-mail-address	"alexandre.loures@ymail.com"
      user-full-name	"Alexandre Loures")

(setq gnus-select-method '(nntp "news.gwene.org"))
(add-to-list 'gnus-secondary-select-methods '(nnml ""))

(setq mail-sources '((pop :server "pop.mail.yahoo.com"
			  :port 995
                          :user "alexandre.loures@ymail.com"
                          :password "mypasswordsecret"
			  :leave 14
			  :stream ssl)))

(setq send-mail-function		'smtpmail-send-it
      message-send-mail-function	'smtpmail-send-it
      smtpmail-smtp-server		"smtp.mail.yahoo.com"
      smtpmail-stream-type              'ssl
      smtpmail-smtp-service             465)

(setq nnmail-split-methods '(
			     ("SAS" "^From:.*marketingbrasil@sas.com")
			     ("Stata" "^From:.*service@stata.com")
			     ("ResearchGate" "^From:.*no-reply@researchgatemail.net")
			     ("FSF" "^From:.*info@fsf.org")
                             ("SPAM" "^From:.*noreply@facebookmail.com")
			     ("Other" "")
			     ))

(setq gnus-signature-file)

;; this does a call to gnus-group-get-new-news

(gnus-demon-add-handler 'gnus-demon-scan-news 10 t)

;; defining the number of columns (the width) of the body of the email as well as the layout of the text
;; (justified), that is, formatting the e-mail appearance

(defun my-message-mode-setup ()
  (setq fill-column 180)
  (turn-on-auto-fill))
(add-hook 'message-mode-hook 'my-message-mode-setup)

;;; the following settings is for Gnus to notify you of receiving new mail
;;; you must first place the file avaible in: 'https://www.emacswiki.org/emacs/download/gnus-notify.el' where 
;;; Gnus can locate it
;;; site where I got help: 'https://stackoverflow.com/questions/1053245/new-mail-notifications-in-gnus-for-emacs'

(setq gnus-parameters
      '(("INBOX"
	 (gnus-use-adaptive-scoring nil)
	 (gnus-use-scoring nil)
	 (visible . t)
	 (display . all)
	 (modeline-notify . t)
	 )))
#+END_SRC

In turn, to send mail the (=~/.authinfo=) file is configured as follows:

#+BEGIN_SRC
machine smtp.mail.yahoo.com login alexandre.loures@ymail.com password mypasswordsecret
#+END_SRC

** Signature

This is my file (=~/.signature=) to add a signature to the end of the mail.

#+BEGIN_SRC
Alexandre Loures
Department of Rural Economy
Federal University of Vicosa
www.economia-aplicada.ufv.br
www.rodriguesloures.com
#+END_SRC

** Autocomplete the address of the mails

This is my file (=~/.mailrc=) to autocomplete the address of the mails. Once you have the (=~/.mailrc=) file just put the alias (To; CC and CCo) and type =spc= so that the mail is automatically completed. 

#+BEGIN_SRC
alias loures "Alexandre Loures <none@example.com>"

alias arl "Loures <none@example.com>"

alias father "Father <none@example.net>"

alias mother "Mother <none@example.org>"
#+END_SRC
** Some commands:

=ZZ=             From inside a group go back to the buffer group

=C-c C-f C-c=    Show a Cc

=C-c C-f C-b=    Show a Bcc

=L=              Show all groups (with read and unread emails)

=C-u RET=        Enter a group and show all emails (read and unread)

=C-u M-g=        Within a group shows all emails (read and unread)

=S r=            Reply to the author of the current article

=S w=            Reply that goes out to all people listed in the *To* and *Cc*


